appVersion=0.2.1
android.useAndroidX=true
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.vfs.watch=true
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
