name: Sesame-AG Dev自动打包

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

# 提前解决Node.js20废弃警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # 解决git exit 128错误，拉取完整git历史
          submodules: true # 拉取项目子模块，本项目依赖子模块必须开启
      
      - name: 配置JDK17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temurin

      - name: 授予Gradle执行权限（避免权限报错）
        run: chmod +x ./gradlew
      
      - name: Gradle编译Release APK
        run: ./gradlew assembleRelease
      
      - name: 保存安装包
        uses: actions/upload-artifact@v5
        with:
          name: Sesame-AG-Dev编译APK
          # 路径正确写在一行，不要再拆分
          path: app/build/outputs/apk/release/*.apk