name: Sesame-AG Dev自动打包

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

# 解决Node.js20废弃警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目主代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: 补全缺失的libxposed子模块
        run: |
          mkdir -p libxposed
          git clone https://github.com/libxposed/api.git libxposed/api
      
      - name: 配置JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: 授予Gradle执行权限
        run: chmod +x ./gradlew
      
      - name: Gradle编译Release APK
        run: ./gradlew assembleRelease
      
      - name: 保存安装包
        uses: actions/upload-artifact@v4
        with:
          name: Sesame-AG-Dev编译APK
          path: app/build/outputs/apk/release/*.apk